name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Go setup
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Install build dependencies
        run: make deps

      - name: Code build
        run: make build

      - name: Code format
        run: make format && git diff --exit-code
      
      - name: Code test
        run: make test
      
      - name: Code lint
        run: make lint

      - name: Tagger
        uses: agukrapo/tagger@v0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assets: bin/*
